### PR TITLE
fixed sharp edges climbability checking;

### PR DESCRIPTION
**Pull request by TeslaRus**
found that "middle hands pos" may contains too low z coordinate in some
animations; the solution is not full: 
- not all cases tested; 
- Lara can climb on through a wall;
- Character_GetMiddleHandsPos have to return point with z_max, not with z_middle;

### CODE REVIEW

**Comment by vvs-** [comment]
I can't find a test case for this issue. Could you provide one, please?

**Comment by TeslaRus** [comment]
to check Character_CheckClimbability in unit test: test level and some cases of test_from, test_to are required; returned collision_info will be criteria; the level have to contain some climbable edges and character entity (really needed only character settings...);

**Comment by vvs-** [comment]
So, are there no such existing levels in TR? If not then perhaps someone could create a test level? @Lwmte, could you make one, please?

Also, there were some test levels in `backup` which need to be resurrected.

**Comment by TeslaRus** [comment]
ok, this time I trying to build OT with cygwin, and SDL2 makes a problem for linker (sdl redefines main, so linker troubles); ok, I will see test levels from backup, and one of them will be used as a default (empty engine looks not so good);

**Comment by vvs-** [comment]
There is another test level which is buried in issues: https://github.com/opentomb/OpenTomb/issues/275#issuecomment-131443375

**Pull request merged**
