### PR TITLE
VS2015 Buildability

### PR DESCRIPTION
**Pull request by stohrendorf**
This finally allows to create a VS2015 solution and make OpenTomb buildable and runnable in it.

### CODE REVIEW

**Comment by Gh0stblade** [comment]
Great work, this is something I've always wanted to become possible! I approve.

**Comment by vvs-** [comment]
It doesn't link on Linux, at least SDL2 detection is broken.

**Comment by stohrendorf** [comment]
Can't confirm this. It detects SDL2, compiles, links, and runs here.

**Comment by vvs-** [comment]
But it doesn't link here. Fedora 21 32-bit.

I bet it'd quickly become broken after merge because nobody will test it.

**Comment by stohrendorf** [comment]
Where is your SDL2 library located and where are the headers? And what exactly does "doesn't link" mean, i.e. are there missing symbols, or is the library not found? Maybe the find script needs some extension.

**Comment by vvs-** [comment]
Fixed by removing `SDL2MAIN_LIBRARY` from `CMakeLists.txt`.

**Comment by stohrendorf** [comment]
That doesn't answer my question.

**Comment by vvs-** [comment]
Well, it doesn't find SDL2MAIN_LIBRARY, so it can't link it. There is no such library in Fedora.

**Comment by stohrendorf** [comment]
OK, that brings me to a solution, because especially on windows, sdl2main *is* needed, yet on other platforms, it is optional, but often enough it is present as a stub library. I'll see if I can make it optional.

**Comment by stohrendorf** [comment]
Turns out it was already handled by the FindSDL2.cmake.

**Comment by vvs-** [comment]
It  doesn't work anyway. I get `inf` instead of the FPS indicator. I have no logo or splash screens. The level maps are not loading for some reason and there are no any error messages.

**Comment by stohrendorf** [comment]
I guess I found the problem, but I can't test it right now. Probably MSVC treats `1e3` as float, while GCC treats it as `int`, which caused a wrong `Sys_FloatTime` result.

**Comment by vvs-** [comment]
While `setgamef` doesn't work I'm able to load maps by name. But everything is frozen.

**Comment by stohrendorf** [comment]
Does it show somewhat correct FPS information?

**Comment by vvs-** [comment]
No, it's still `inf`. It briefly shows 200 fps at the beginning.

**Comment by stohrendorf** [comment]
This is the last try to fix it here from windows. When I can boot to linux again, I'll try to fix it there if this doesn't solve the problem.

**Comment by vvs-** [comment]
Seems to be working again. But I didn't thoroughly test it.

**Comment by vvs-** [comment]
I see that time is now in milliseconds while `gettimeofday` returns time with a microsecond precision.

**Comment by vvs-** [comment]
Now everything looks like in `master`.

**Pull request merged**
