### PR TITLE
Alt room refactoring

### PR DESCRIPTION
**Pull request by TeslaRus**
alt rooms used only for content store;
no more "check flip" functions: only real_room ptr or Sector_CheckRealRoom(...);
Room collision generation is workaround, because real tween collision between rooms depend on room combination (alt / real version) so there are two ways: 1) generate additional tween collision meshes for ALL room / real room combinations; 2) generate on fly after every World_SetFlipState();
UPD: only 2) is sane solution;

### CODE REVIEW

**Comment by vvs-** [comment]
In _Tomb of Qualopec_ portal from room 18 to room 11 doesn't work, Lara can't pass.

In _Cistern_ swapping to water room doesn't transfer its water attribute, only the water surface is seen.

#343 is still valid.

In altroom4 test level Lara starts in a wrong room.

**Comment by TeslaRus** [comment]
"In altroom1 test level room swapping doesn't work." - I test it, it does not works because I stay as is swapping sequence (if I swap 3 cycled rooms from 1 to 3, then 1 made full turn and no changes for 1 (real room), 2 and 3 changed). How to correctly swap rooms? does I need to mark **next_alt_room** as swapped / unswapped (like world.cpp str 976)?

**Comment by TeslaRus** [comment]
> In Cistern swapping to water room doesn't transfer its water attribute, only the water surface is seen.
Thx, forgot flags

**Comment by TeslaRus** [comment]
about altroom initial pickable objects state: in Natla's mines pistols and large med is accessible before 3 puzzle hole  activation (or it is an additional script with objects enabling / disabling)?

**Comment by vvs-** [comment]
> 1 made full turn and no changes for 1 (real room), 2 and 3 changed)
Are you sure it's altroom1? There is only two that should be swapped. One has a raised cube and the other doesn't.

**Comment by TeslaRus** [comment]
if rooms are cycled, swapping does twice, so no visible changes

**Comment by TeslaRus** [comment]
altroom1 passed;
room_flags fixed;
physics crash fixed;
World_FindRoomByPosCogerrence(...) fixed;

**Comment by vvs-** [comment]
There is something wrong with the water rooms in _Cistern_. After swapping rooms, Lara can still swim in the air after climbing from water.

There are no changes in _Tomb of Qualopec_ and altroom4 also.

**Comment by vvs-** [comment]
> about altroom initial pickable objects state: in Natla's mines pistols and large med is accessible before 3 puzzle hole activation (or it is an additional script with objects enabling / disabling)?

I'm not sure. But in TR3 NPC inventory is kept under their feet. Maybe that's the same?

**Comment by vvs-** [comment]
> about altroom initial pickable objects state: in Natla's mines pistols and large med is accessible before 3 puzzle hole activation (or it is an additional script with objects enabling / disabling)?

This is actually described in #259.

**Comment by vvs-** [comment]
In _Natla's Mines_ camera repeatedly bumps into invisible boat static near waterfall.

**Comment by vvs-** [comment]
In _Natla's Mines_ there is something wrong with sector `4,1` in room 28. Lara consistently lose her room ownership and falls out, sometimes into room 20 and sometimes out of level mesh.

**Comment by vvs-** [comment]
altroom2 test was (and still is) broken in 1048ab7c1434340e1793bc5765486f0a6d5c13a3.

**Comment by TeslaRus** [comment]
thanks for info... next I will fix - alt / normal room collision filter (disable / enable function too). 
last commit - only tweens generation fix (waterfall in TR1 map 3)

**Comment by vvs-** [comment]
Seems mature to me. All recent issues that previously appeared in this PR were fixed. #343, #386 and altroom4 are the only problems that were not addressed yet. But maybe that do not belong to this PR after all, I'm not sure.

**Comment by TeslaRus** [comment]
Thanks for feedback - it helps to fix serious bugs in early stage

**Comment by vvs-** [comment]
"altroom4 test can not been passed, because at same time only one room (in alt room sequence) is available for entities / rendering"

Then it should be changed, because in the Core engine this level just works as expected. So, obviously there is no such limitation. Camera there sees only one room at a time, depending on its direction relative to a portal.

**Pull request merged**
