### PR TITLE
TRS3 - complete flipeffect guide

### PR DESCRIPTION
**Pull request by Lwmte**
I did my best to describe whole flipeffect concept, as well as each flipeffect for every game version. Only two unknowns are two mysterious flipeffects 31 and 33 in TR5. I hope someone will do some research on this.

### CODE REVIEW

**Comment by TeslaRus** [comment]
lgtm

**Comment by Lwmte** [comment]
So, any other suggestions or comments?
Do we need, for ex., exact track IDs for ASSAULT_FINISH flipeffect, or assume that "who needs that, will get that with IDA/Olly"?
If not, I'm going to merge it.

**Comment by vvs-** [comment]
I'd say "merge it".

**Comment by TeslaRus** [comment]
let us reduce the number of pull request by merging this one ;-)

**Pull request merged**
