### PR TITLE
FMV fixes.

### PR DESCRIPTION
**Pull request by RICCIARDI-Adrien**
Following videos were crashing the game when trying to play them (it was due to unsupported audio format) :
* data/tr1/fmv/CAFE.RPL
* data/tr1/fmv/CANYON.RPL
* data/tr1/fmv/LIFT.RPL
* data/tr1/fmv/PRISON.RPL

Also, FMVs did not started from the beginning.

I'm trying to solve the bug that hangs the game when playing more than one FMV in the row, but you can merge this pull request if it is OK for you.

### CODE REVIEW

**Comment by vvs-** [comment]
Right. They did actually work in the past but become broken at some time before #538.

**Comment by RICCIARDI-Adrien** [comment]
Pull request is ready for merging.

**Comment by TeslaRus** [comment]
Thanks for PR. I need some time to check it (I have little time).
Can not reproduce video play crash.

**Comment by RICCIARDI-Adrien** [comment]
You're welcome.
I just checked and all videos that were crashing contain localized dialogs. All other videos do not have voice. Maybe my french version is 8-bit encoded but the english-one is 16-bit, like the voiceless videos ?

**Comment by vvs-** [comment]
I have no crash either in my English version. But I have a lock-up playing any video for the second time. This is the same bug as in #538 where original reporter had non-reproducible crash on one of his computers.

**Pull request merged**
