### PR TITLE
audio streams loading moved to level loading stage;

### PR DESCRIPTION
**Pull request by TeslaRus**
first stable solution; need time to check it;

### CODE REVIEW

**Comment by vvs-** [comment]
Seems to work, but audio buffers still underflow producing popping sound. `playStream` works fine.

**Comment by TeslaRus** [comment]
I still not understood audio module fine, so I only move loading and storing track source data to the simple separate class. And it does not solve problem fully: if level_autoexec script contains PlayTrack command, then engine hang after level loading...

**Comment by vvs-** [comment]
There is also crash in samples override (it was already there before this PR):
```
*** Error in `./OpenTomb': double free or corruption (!prev): 0x0a1b6a20 ***
======= Backtrace: =========
/lib/libc.so.6(+0x6b1bb)[0xb71a91bb]
/lib/libc.so.6(+0x73e7a)[0xb71b1e7a]
/lib/libc.so.6(cfree+0x50)[0xb71b5330]
/lib/libc.so.6(fclose+0x177)[0xb719f527]
/lib/libSDL2-2.0.so.0(+0x4a2a3)[0xb76832a3]
./OpenTomb(_Z30Audio_LoadALbufferFromWAV_FilejPKc+0x45)[0x808e455]
./OpenTomb(_Z26Audio_LoadOverridedSamplesv+0xee)[0x808e5ce]
./OpenTomb(_Z16Audio_GenSamplesP8VT_Level+0x427)[0x808ea57]
./OpenTomb(_Z10World_OpenP8VT_Level+0x19a)[0x80e447a]
./OpenTomb(_Z18Engine_LoadPCLevelPKc+0x2c9)[0x8097d59]
./OpenTomb(_Z14Engine_LoadMapPKc+0x91)[0x8097e61]
./OpenTomb(_Z11Gameflow_Dov+0x154)[0x809f7f4]
./OpenTomb(_Z15Engine_MainLoopv+0xbd)[0x809773d]
./OpenTomb(main+0x23)[0x8085c13]
/lib/libc.so.6(__libc_start_main+0xf5)[0xb7156545]
./OpenTomb[0x80860c3]
```

It would be helpful to get assistance from @Lwmte.

**Comment by vvs-** [comment]
Ok. It turned out that audio buffers underflow happens only after second invocation of `playStream`. E.g. try `setgamef(1,1)` and `playStream(8)`. Play it again after the stream finished playing without ever leaving the console.

**Comment by TeslaRus** [comment]
aha - stream 8 plays again, but glitched (~paused 1 sec every 3 sec);
thanks for reproduce info :-)

**Comment by TeslaRus** [comment]
audio streaming in audio module will be rewritten...

**Pull request merged**
