### PR TITLE
Gui refactoring

### PR DESCRIPTION
**Pull request by TeslaRus**
console refactored;
gui module decomposed;

### CODE REVIEW

**Comment by vvs-** [comment]
Font rendering in inventory is broken.

**Comment by TeslaRus** [comment]
fixed in https://github.com/opentomb/OpenTomb/pull/465/commits/0cf61d065c341684a8029c15250f88a23f9eb356
to list console history try PAGE_UP PAGE_DOWN keys in console

**Comment by vvs-** [comment]
Seems that Up and Down keys invoke the first command instead of the last.

**Comment by TeslaRus** [comment]
fixed.

**Pull request merged**
