### PR TITLE
[NOT_FOR_MERGING] Fix OpenAL

### PR DESCRIPTION
**Pull request by vvs-**
This commit should be in the previous PR, not a separate one.

### CODE REVIEW

**Comment by vvs-** [comment]
Please, do not merge any PR until it is considered working.

I just don't understand why there are always different results on Travis? I have no such errors with Lua. How am I supposed to test it then?

**Comment by vvs-** [comment]
The differences in Travis build system are just too big. I didn't get these errors even on my old system where it produced similar errors in `core`. Wouldn't it be easier to just upgrade to a more recent build environment on Travis? @stohrendorf, was there some reason why you chose that particular Ubuntu version?

**Comment by vvs-** [comment]
Great, gcc build works now, but clang doesn't. I have no means to fix that. I propose to turn it off in travis configuration. Any objections?

**Comment by stohrendorf** [comment]
@vvs I remember a discussion about system requirements, and the result of it was something like "we need to make sure it runs on old and weak systems", so Ubuntu 14.04 already seemed like a risky choice ;)

**Comment by stltomb** [comment]
@vvs- It doesn't compile because the check `if(CMAKE_COMPILER_IS_GNUCXX AND CMAKE_COMPILER_IS_GNUCC)` only works for gcc, and not Clang.
Because of that, the compiler options like _-std=c++11_ aren't supplied to Clang.

[see here](https://stackoverflow.com/questions/10046114/in-cmake-how-can-i-test-if-the-compiler-is-clang)

**Comment by vvs-** [comment]
> "we need to make sure it runs on old and weak systems"

"Runs" and "builds" are different things. Shouldn't the whole purpose of Travis CI be in compilation alone?

> It doesn't compile because the check if(CMAKE_COMPILER_IS_GNUCXX AND CMAKE_COMPILER_IS_GNUCC) only works for gcc, and not Clang.

Good catch. But I still won't be able to test it locally :frowning:

**Comment by stohrendorf** [comment]
> "Runs" and "builds" are different things.

Not necessarily. If you require a very recent compiler (or even libs) to build OpenTomb, chances are pretty high that it won't run on older systems because of system library dependencies. So if you want to ensure that it (most probably) will run on older systems, you need an older system to compile it.

**Comment by vvs-** [comment]
That's impossible to support. The question was: is it reasonable to require users to update their systems in order to be able to run OpenTomb? And my position was that it should be a requirement _only_ if it's _absolutely_ necessary for an OpenTomb to run. There are requirements that can't be justified on these grounds.

**Comment by vvs-** [comment]
> I'd rather fix the if than provisioning these flags generally (and maybe also remove that obsolete comment). If someone (like me) wants to try out MSVC some day, this will prevent a compilation.

And you are free to do that. But I'm unable to test such changes, so don't expect me to do that blindly.

**Comment by vvs-** [comment]
`Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression`
So, it's impossible to fix without upgrading Travis.

**Comment by stohrendorf** [comment]
According to https://cmake.org/cmake/help/v3.0/variable/CMAKE_LANG_COMPILER_ID.html that expression should be something like
```cmake
if((CMAKE_COMPILER_IS_GNUCXX AND CMAKE_COMPILER_IS_GNUCC) OR (CMAKE_CXX_COMPILER_ID STREQUAL "Clang"))
```

**Comment by vvs-** [comment]
That's right, but I can't test it. If there will be a typo I can't notice that and it would silently fail on a user system.

**Comment by stltomb** [comment]
> So, it's impossible to fix without upgrading Travis.

@vvs- It would seem so (without using the `CMAKE_CXX_FLAGS` and `CMAKE_C_FLAGS`).

That CMake version must be ancient. Trusty repos have version 2.8.12 that was released on Oct 8, 2013. The `COMPILE_LANGUAGE` feature was merged on March 9, 2015.

**Comment by vvs-** [comment]
Could you change Trusty to something more recent? I believe that it's completely justified in this case.

**Comment by vvs-** [comment]
Looks like the only way to solve this is to install CMake 3.3+ from PPA.

**Comment by vvs-** [comment]
Success! :fireworks:

But this is a nasty workaround and we should find a better solution.

**Comment by vvs-** [comment]
Feel free to merge this PR if there are no other objections.

**Comment by stohrendorf** [comment]
It's a first working build system that make Travis happy, so if this gets merged, Travis can actually tell if the pull requests are sane or not, which is a huge step forward. I'd go for it, but keep in mind that it needs cleanup.

**Pull request merged**
