### PR TITLE
Rpl

### PR DESCRIPTION
**Pull request by TeslaRus**
Added RPL video playing support;
game logic bug fixing;
audio tracks playing work with big bugs... will be fixed in other branch (audio refactoring, or master, depend on solution complexity);

### CODE REVIEW

**Comment by TeslaRus** [comment]
130 codec... it will be easy to add this =) most complex problem was solved: streaming structures and video / audio rendering. Audio codec is PCM AS IS (memcpy codec)

**Comment by vvs-** [comment]
BTW, there is Bink video/audio codec for TR5, but it's too early to even speak about it.

**Comment by TeslaRus** [comment]
ffmpeg has that codecs too, but I do not know how much code I have to port

**Comment by vvs-** [comment]
BTW, I forgot to mention that TR3 used ADPCM for FMV, so no audio.

**Comment by TeslaRus** [comment]
heh... Eidos logo works (TR3), other fmv uses other audio codecs... PCM, ADPCM... I will port adpcm too

**Comment by vvs-** [comment]
Yep. Logo.rpl is the same for TR2 and TR3. Other videos use different audio codecs.

**Pull request merged**
