### PR TITLE
Glew

### PR DESCRIPTION
**Pull request by vvs-**
That's Glew support extracted from `luastate` branch. It seems self contained.

### CODE REVIEW

**Comment by Lwmte** [comment]
Hmm... So we can safely merge it into master?

**Comment by Lwmte** [comment]
P.S.: I saw some lines like this **#include <bullet/LinearMath/btScalar.h>** , while in some files there are still **#include "bullet/LinearMath/btScalar.h"** , is it right?

**Comment by vvs-** [comment]
> So we can safely merge it into master?

That's for you all to decide. It's a trivial enough change, it compiles and was tested by me and cochrane.

> P.S.: I saw some lines like this #include <bullet/LinearMath/btScalar.h> , while in some files there are still #include "bullet/LinearMath/btScalar.h", is it right?

The author is stohrendorf so I can't speak for him. But if you feel that's not right we can add another commit to this PR or it can be fixed later. You can even pull this to your local repository, edit it there and create a new PR.

**Comment by Lwmte** [comment]
Ok, sorry, I just not used to Github yet! :)

**Comment by Lwmte** [comment]
Regarding this `""` vs `<>` issue, I honestly don't know what's valid right now. As Bullet was removed from source code and reimplemented as a link, I can assume we should get rid of `""` completely in favor of `<>`?

**Comment by vvs-** [comment]
Honestly, I don't know. It works, but the proper solution for external dependencies isn't decided yet. Aren't #115 and #120 just for that purpose?

**Comment by vvs-** [comment]
Actually, I found some issues with just these two commits. I have no font or debug information anymore. But obviously that was fixed by some other commit. I'll try to find it tomorrow.

**Comment by vvs-** [comment]
Found a fix.

There is still one bug remaining: debug information doesn't work. But it's present in `luastate` and `macfix-luastate` as well, so I can't do anything about it.

**Pull request closed without merging**
