### PR TITLE
use in-tree built bullet

### PR DESCRIPTION
**Pull request by stohrendorf**
builds bullet in-tree and forces the usage of the in-tree build bullet version

### CODE REVIEW

**Comment by cochrane** [comment]
Looks good to me. Initial test confirms it works well for bullet. If this gets accepted, I'll probably try and use that approach for other libraries we rely on as well.

**Comment by stohrendorf** [comment]
I had a thought about it, and maybe it's even better to put the bootstrapping parts into a separate repository, used only for preparing the build environment. This way we would keep the main tree free from external code at all, and that "build env setup" could get more elaborate, e.g. by setting up also SDL2, sndfile, etc. for users of MSVC.

**Comment by cochrane** [comment]
Yeah, that might be a good idea. Right now this works, but I can't directly generate an Xcode project, and I've found cmake's ability to create projects for use by IDEs very useful.

**Comment by stohrendorf** [comment]
What is the problem when trying to create an XCode project? Is it this approach in general, or something else?

**Comment by cochrane** [comment]
I get an error that no Xcode project can be generated for bullet. Not sure why, or why I should care (since I don't need one for bullet anyway). Maybe it is possible to generate one now that bullet has been built. I may need to do more experimentation when I'm back from work.

**Comment by stohrendorf** [comment]
This is because the bootstrapping inherits the project type. It can only be cleanly solved (without overwriting/hacking the cmake generation and make programs for bullet and openal) by moving the bootstrapping out of the main project.

**Comment by vvs-** [comment]
It does work here. I didn't notice any problems.

**Comment by cochrane** [comment]
> This is because the bootstrapping inherits the project type. It can only be cleanly solved (without overwriting/hacking the cmake generation and make programs for bullet and openal) by moving the bootstrapping out of the main project.

That does sound reasonable.

**Comment by stohrendorf** [comment]
This is deprecated, see #254.

**Pull request closed without merging**
