### PR TITLE
Add acell limits like original

### PR DESCRIPTION
**Pull request by Gh0stblade**

### CODE REVIEW

**Comment by Lwmte** [comment]
Seems like sprint and run speeds are now broken. Lara's acceleration is too low.

Can you provide some examples where these fixes are relevant?

**Comment by Gh0stblade** [comment]
Hi Lwmte! I'm not done just yet. I think i've found something very important related to the speed/acceleration system. If it's confirmed I'll add some more commits with an explanation here so that it can be discussed further.

Cheers.

**Comment by Lwmte** [comment]
Ok, I'll keep an eye on it. Thanks! 
Do you think you can manage integrating speed calculations into freeFalling move type?

**Comment by Lwmte** [comment]
Offtopic: @Gh0stblade - please take a look at #256 :wink:

**Comment by Gh0stblade** [comment]
You mean vertical speed? I believe it is hard coded. I'm currently looking at TR5 and debugging it to see what exactly is going on and why these speed issues are occuring. I'm not sure if it's worth it though since the system is completely different to OpenTomb and probably wouldn't be compatible but if we get the math right, it should still work.

Anyhow, this pull request is being closed. There will be another one.

**Comment by Lwmte** [comment]
No, not vertical speed. I mean that during freeFalling move type, animation speed should be processed as well. If you compare, for example, moveOnFloor code with freeFalling code, you will note that freeFalling is missing that four-part if-then statement ([look at line 1008](https://github.com/opentomb/OpenTomb/blob/master/src/character_controller.cpp#L1008) in character_controller.cpp).

This is the ultimate reason why horizontal speeds are not processed with free falling states (mentioned by @Joey79100 in #28):

> By the way it seems that the speed for animation 95 (ready to grab) is ignored. She's meant to go forward, but in OpenTomb she has no horizontal speed.
> The speed she has when she hits a wall while jumping are ignored too.

**Comment by Lwmte** [comment]
Currently, wall hit animations and animation 95 speeds are done using ugly workarounds.

**Comment by Gh0stblade** [comment]
@Lwmte are you sure? I see the speeds correctly being applied.

**Pull request closed without merging**
