### PR TITLE
Update LICENSE 

### PR DESCRIPTION
**Pull request by agentzero1**
Filipino translation of LICENSE

### CODE REVIEW

**Comment by TeslaRus** [comment]
Why original LICENSE is deleted?

**Comment by agentzero1** [comment]
I dont do anything .

**Comment by agentzero1** [comment]
What do you mean its deleted ? Its still there

**Comment by agentzero1** [comment]
What do you mean its deleted ? Its still there
screenshot_20180218-075616

This is the original

**Comment by agentzero1** [comment]
screenshot_20180218-075607

And my translated

**Comment by agentzero1** [comment]
The english file sir is still present

**Comment by vvs-** [comment]
Apparently you are not proficient with git. The original file is deleted in your pull request. If merged it would delete that file in main repository too. You should restore it first to make merging possible.

**Comment by agentzero1** [comment]
I dont how to do a restoring process

**Comment by agentzero1** [comment]
can you help me

**Comment by vvs-** [comment]
That's easy. Just add that file again to your `patch-2` local branch and push to your GitHub repository. That commit will appear automatically in this pull request.

**Comment by agentzero1** [comment]
Is this correct?

**Comment by TeslaRus** [comment]
license still shows as deleted (+165 **-166**)

**Comment by agentzero1** [comment]
What will I do ? I just follow on what @vvs-  said.

**Comment by vvs-** [comment]
No, you didn't. There were no original English license added, just modifications to translation. Just put that English licanse back were it belongs, use `git add` and `git commit` to record it in history and then `git push` to update GitHub repository branch.

**Pull request closed without merging**
