### PR TITLE
Audio refactoring

### PR DESCRIPTION
**Pull request by TeslaRus**
fixed audio streams cleaning, playing

### CODE REVIEW

**Comment by vvs-** [comment]
`playStream(8)` skips part of the audio stream.

**Comment by TeslaRus** [comment]
playStream(8) - works fine (tested for https://github.com/opentomb/OpenTomb/pull/460/commits/3e25d929f02bc1dfc9ef316cf052db6f2d96e522)

**Comment by vvs-** [comment]
Nope, not for me. Skips on the 23-24s.

**Comment by vvs-** [comment]
The whole 015.ogg should be 64s in total (except silence at the end), but `playStream` lasts only for 40s.

**Comment by TeslaRus** [comment]
yep, thanks - it was really stupid bug - double incrementing for offset, fixed

**Pull request merged**
