### PR TITLE
use libsndfile for ogg loading

### PR DESCRIPTION
**Pull request by stohrendorf**
Related to #115

### CODE REVIEW

**Comment by Lwmte** [comment]
Judging by the code, does it mean that streaming is now possible for *any* file format supported by libsndfile?! If that's the case, we can now safely implement CDAUDIO.WAD support!

**Comment by stohrendorf** [comment]
Yes, this is potentially possible, though the main reason for this was to get rid of the SDL-patched openal code.

**Comment by vvs-** [comment]
OpenTomb now hangs after loading a level with repeated message `Attempt to read a non-integer number of channels`.

**Comment by Lwmte** [comment]
Ok, I understand, I won't touch any pull requests anymore until code gets stable! =)

**Comment by stohrendorf** [comment]
Should be fixed now. At least the TR3 soundtrack plays in the background for me.

**Comment by vvs-** [comment]
> Ok, I understand, I won't touch any pull requests anymore until code gets stable! =)

It'd be perfectly viable if there were several branches. A recommended practice is to have an unstable `devel` and stable `master`.

**Comment by stohrendorf** [comment]
> It'd be perfectly viable if there were several branches. A recommended practice is to have an unstable devel and stable master.

I fully agree. I'm currently only fixing small things in `master` and doing larger fixes and every functional change in a separate branch.

**Pull request merged**
