### PR TITLE
Physics refactoring

### PR DESCRIPTION
**Pull request by TeslaRus**
- physics modules now are in **physics** dir;
- ragdoll and hair moved to their own modules (inside **physics** dir);
- stabilized collision resolving and deleted no_fix_z collision resolving flag;
- ragdoll and hair LUA parsers now are more abstract (less code dependencies);

### CODE REVIEW

**Comment by vvs-** [comment]
Something is broken. Either a jumping trajectory become lower or Lara has now legs collision where it wasn't before. She can't make a running jump to a timed double door in _Caves_.

**Comment by TeslaRus** [comment]
yep, it is no_fix_z disabling... should be solved by the other way

**Comment by vvs-** [comment]
There is another problem. Lara could disappear in noclip mode when out of any room.

**Comment by TeslaRus** [comment]
> Lara could disappear in noclip mode when out of any room.

 - it is normal... Lara become usual entity ~4 month ago...

**Pull request merged**
