### PR TITLE
Filipino Translation of TODO.md

### PR DESCRIPTION
**Pull request by Cyyy1998**

### CODE REVIEW

**Comment by Cyyy1998** [comment]
I hope is it correct

**Comment by Cyyy1998** [comment]
Ready for review sir

**Comment by TeslaRus** [comment]
Yes, now it is correct. I have to check terminology translation (i.e. Bullet Physics -> Bullet Physics, library names must not be translated)
I do not know Filipino unfortunately

**Comment by Cyyy1998** [comment]
Done changing

**Comment by Cyyy1998** [comment]
Ready for merging

**Pull request merged**
