### PR TITLE
Collision shapes

### PR DESCRIPTION
**Pull request by TeslaRus**
fixed collision shape options single_box, single_sphere;
added options for ghosts shapes tuning;

### CODE REVIEW

**Comment by vvs-** [comment]
It fixed stuck boulder in _Atlantean Stronghold_.

**Comment by TeslaRus** [comment]
% ) cool... Idid not mean that fixes something except collision shape flags working

**Comment by vvs-** [comment]
I don't know if it belongs to this PR or not, but recent changes to penetration test produced weird bug: Lara can't stand on some meshes. Try running forward from this position:
screen_00001

**Comment by TeslaRus** [comment]
overlapped rooms list generation... next fix fixes that issue, but it adds Atlantis collision bug for 47 - 84 rooms (I have to add script function for near / overlapped list modification);

**Comment by TeslaRus** [comment]
found way without scripts using... but it is hacky too...

**Comment by vvs-** [comment]
Yes, and in room 2 of _Sanctuary of the Scion_ and many others.

**Comment by vvs-** [comment]
While it fixed boulder in _Atlantean Stronghold_ it also broke another boulder in _City of Khamoon_.

**Comment by TeslaRus** [comment]
now by default connected rooms can not been overlapped, but can after direct script instruction: addRoomToOverlappedList
it is better to fix rarely bloody mess collisions troubles by some level scripts than drops through the map...

**Comment by vvs-** [comment]
What does it supposed to change? Actually, I don't see any improvements. There are still overlapped rooms rendered incorrectly and Lara still can't climb in room 84.

**Comment by TeslaRus** [comment]
it allows to separate bugs... and fix them... but it may affect other physics (TR1, MAP 10, climb left / right still works)

**Comment by vvs-** [comment]
I've tried `addToOverlappedRoomList(74,78)` in _Tomb of Tihocan_. The rendering is partially fixed, but collisions are not.

**Comment by TeslaRus** [comment]
aaa, it is another type of bug, I know how to parse it and filter collision, but it will be very expensive operation...

**Comment by TeslaRus** [comment]
addRoomToOverlappedList(77, 78); - it helps

**Comment by vvs-** [comment]
The rendering is still buggy, though. You can still see top of the overlapping room sometimes:
screen_00000

**Comment by TeslaRus** [comment]
this time I have no any sane ideas how to fix it (insane - add to portals additional flag to force stencil test usage)

**Comment by TeslaRus** [comment]
addRoomToOverlappedList(77, 78); - it helps but produce a graphic bug (camera may come out of room)

**Pull request merged**
