### PR TITLE
Trosettastone

### PR DESCRIPTION
**Pull request by stohrendorf**
asciidoc conversion of trosettastone for further improvability.

### CODE REVIEW

**Comment by Lwmte** [comment]
There is actually more recent TRosettaStone edit by E. Popov: http://www.evpopov.com/perso/dl/TRStone/TRLevelFileFormat.html

However, it is much harder to maintain, cause it uses some "smart" formatting...

**Comment by vvs-** [comment]
Shouldn't such docs go to the Wiki? BTW, [openraider](https://github.com/xythobuz/openraider) has it in their Wiki. Don't know about its' age and version, though.

**Comment by stohrendorf** [comment]
I agree that the wiki is logically a better place, but markdown is too limited in semantic (and visual) markup and github's asciidoc is just some markdown flavor. Otherwise I had created a wiki page.

**Comment by Lwmte** [comment]
I also thought about creating wiki for TR documentation, but seems that Github wiki is too simple for this - no categories, no advanced formatting, etc. So I scrapped this idea.

Don't bother with this Popov version, changes are actually not that big, and I already have another TRosettaStone version that I once wrote (it's not on the Net right now). I will integrate both into your remake, plus merge some recent info from TRF (like blending modes, reverb info, specific data types etc.). All in all, we should get comperhensive doc in the end. Also, there are seperate docs about cutseq.pak file format, cdaudio.wad file format, etc., so we should integrate them as well.

**Pull request merged**
