### PR TITLE
Documentation update from TombLevBauer's notes

### PR DESCRIPTION
**Pull request by Lwmte**
Since I finally managed to get asciidoc up and running, I'm merging into TRS3 some information from TombLevBauer's observation notes. You can find a link to the document in this forum post: http://www.tombraiderforums.com/showpost.php?p=7498021&postcount=62

I purposefully ignored info regarding NGLE, cause I don't want to plague TRS3 with NGLE information at the moment.

Please review TombLevBauer's document and see if I missed something (particularly paragraphs 1 and 4, not sure if it's needed to be covered in TRS3).

### CODE REVIEW

**Comment by TeslaRus** [comment]
no comments

**Comment by vvs-** [comment]
I'm not an expert in these matters. You know better.

**Comment by stohrendorf** [comment]
Paragraph 1 is in my opinion an editor detail and does not affect engine behaviour; paragraph 4 only says that the root bone always is at offset (0,0,0), and that at the end there is probably junk written by the editor, but there is no real proof that these values really don't mean anything.

**Comment by TeslaRus** [comment]
lgtm 
You know docs better

**Comment by Lwmte** [comment]
Ok, anyone willing to merge this pull request, or I must do some other actions to confirm that merge is possible?

**Comment by TeslaRus** [comment]
if I write lgtm or something - You can merge it;
Or if You want I merge it (or somebody other) please write about it (please merge it or something like)

**Pull request merged**
