### PR TITLE
Optional FIND_PACKAGE for SDL, for systems without pkgconfig

### PR DESCRIPTION
**Pull request by ablepharus**
Cleaned up

### CODE REVIEW

**Comment by vvs-** [comment]
It looks clean now. But I can't test it because I don't use Windows. Somebody who use it should test and merge this PR.

**Comment by Lwmte** [comment]
It compiled fine, except I have no sound and no loading screens. I think I'll merge it anyway, as there's no other way to compile it in Windows right now.

**Comment by vvs-** [comment]
You can try my `stability_fixes` branch where all questionable commits are reverted. It has textures, sound and no crashes.

**Comment by ablepharus** [comment]
I am sorry, this PR is erroneous, I forgot to include FindSDL and FindSDLImage files

**Comment by vvs-** [comment]
Then just create a new PR with a fix.

**Pull request merged**
