### PR TITLE
Filipino translation for generic.lua

### PR DESCRIPTION
**Pull request by Cyyy1998**
Good day sir,

I translated it to Filipino language.

### CODE REVIEW

**Comment by Cyyy1998** [comment]
Im still waiting for your positive response sir.

**Comment by TeslaRus** [comment]
Hi! scripts/strings/english/generic.lua looks like English version words will be overridden by Filipino words?
I.E.:
 strings[000] = "New Game";
+strings[000] = "Bagong Laro";
 strings[001] = "Select Game";
+strings[001] = "Piliin ang Laro";
....

**Comment by Cyyy1998** [comment]
Actually sir its just the right translation for that word

**Comment by TeslaRus** [comment]
I mean translation should be added (and can be selected by config), but not replaces original:
I.E. adding "scripts/strings/filipino/generic.lua" and updating lang config will not broke original EN translation.

**Comment by Cyyy1998** [comment]
I'll fixed all the problems waiting for your review.

**Comment by TeslaRus** [comment]
Please:
 1) create "scripts/strings/filipino/" folder and place place translation (generic.lua and global_items.lua) there;
 2) delete tabs or replace them by spaces (project code style);

**Comment by TeslaRus** [comment]
merged in #520

**Pull request closed without merging**
