### PR TITLE
Added Linux and Windows CI builds using GitHub Actions

### PR DESCRIPTION
**Pull request by RICCIARDI-Adrien**
Windows build should also be easier even for developing purposes.

### CODE REVIEW

**Comment by TeslaRus** [comment]
try this AL internal, please https://github.com/TeslaRus/OpenTomb/tree/master/extern/al

**Comment by RICCIARDI-Adrien** [comment]
OK.
What C files did you compile ? All the ones contained in `al` subdirectories ?
May I add a CMakeFiles.txt to `al` directory ?

**Comment by TeslaRus** [comment]
yes, all files
May I add a CMakeFiles.txt to al directory ? - ok )

**Comment by RICCIARDI-Adrien** [comment]
@TeslaRus, are you using MinGW on Cygwin ?
It seems that Windows threads have been removed from your OpenAL version, only pthreads are left.

**Comment by TeslaRus** [comment]
yes, mingw has pthreads library (cut version, but enough for AL)

**Comment by RICCIARDI-Adrien** [comment]
New OpenAL is now fully integrated. It is statically linked to avoid deploying one more DLL.

**Comment by vvs-** [comment]
I've just checked the result: OpenTomb repository size has doubled because of the Windows binaries. I think that was not a good idea, because git is really bad at handling binaries. I'd split those away or this blow up could become a problem with time.

**Comment by vvs-** [comment]
Reverted as per discussion in #600.

**Pull request merged**
